### ISSUE TITLE
Arrows are not displaying in questionAdmin

### ISSUE THREAD

**Issue by MatthiasHarvey** [MatthiasHarvey/pinocchio#3]
![image](https://cloud.githubusercontent.com/assets/8530889/8766686/72480b6a-2e42-11e5-9500-1256747199d1.png)

Probably just linking to the CSS with the glyphicons. Just testing issues out.

**Comment by rendi619** [comment]
Hi please insure that you have the correct bootstrap libraries downloaded
or as a online reference.
Regards
