### ISSUE TITLE
Implement Question Admin page

### ISSUE THREAD

**Issue by MatthiasHarvey** [MatthiasHarvey/pinocchio#5]
As shown in the interface branch.

- [x] Sending through question text
- [x] Sending through type
- [x] Sending through grouping
- [x] Sending through choice data
- [x] Sending through rank data
- [x] Sending through rate data
- [x] Sending through freeform data
- [x] Implement add button
- [x] Rank should not have none grouping
- [x] Swap grouping and type (So label's box should also be on the left)

**Comment by MatthiasHarvey** [comment]
@Jason-vh you can check what I've done here so far, then look at how we can send through the question specifics, like sending through the actual choices, ranks etc.

Also, we should implement that add button.

**Comment by Jason-vh** [comment]
I've sent through the choice data, but I'm not sure how it should be saved to the DB:
Should I create a new record for each Choice? 
What is the Header model for, and what goes in its 'text'? 
Should I create a new Header model for each group of Choices?

**Comment by MatthiasHarvey** [comment]
Yes, a new record for each choice. 
I can't remember exactly what the headers were for, but for now just link it to an existing one. I will find out and let you know.
