### ISSUE TITLE
Create page for viewing questions

### ISSUE THREAD

**Issue by MatthiasHarvey** [MatthiasHarvey/pinocchio#7]
This page should look like the maintain users part of the user admin page, but instead list all the questions with their types and groupings.

**Comment by MatthiasHarvey** [comment]
@nigelmpofu You can try implement this. Just ask if you have any questions.

**Comment by MatthiasHarvey** [comment]
@nigelmpofu Have you managed to implement anything here? Otherwise, @Jason-vh said that he managed to get some basic displaying working, so he can push that if that's fine with you

**Comment by nigelmpofu** [comment]
I have pushed my latest changes, made a few user interface tweaks to give a better appearance, questions can be edited and deleted (with confirmation), there is a link to a page that handles the creation of a new question

**Comment by MatthiasHarvey** [comment]
Nice work. Can you create a pull request?

**Comment by MatthiasHarvey** [comment]
Decided to merge this question list with the question admin page #16
